name: generate_key_nfe
description: Generate Key NFE.
version: 0.0.1
repository: https://github.com/arivanjuniordev/generate_key_nfe
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  modulo11: 0.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
